---
# groups are not supported yet
groups:
  testgroup:
    expires: 1590925427

users:
  testuser:
    group: testgroup # optional
    password:
      type: plain # or: argon2
      password: plain_text_password
    expires: 1590925427

  testuser2:
    password:
      type: argon2
      password: $argon2i$v=19$m=4096,t=3,p=1$MDEyMzQ1Njc4OQ$olhpdTlEtA/vrolxbzIHZf29IsTflonzjnTDMkS7BCU

# TODO: How to handle this in order in Yaml?
# regexp_users:
#   /.*/:
#     # you must provide either password or token, but
#     # they can be left empty
#     password: ''

databases:
  somedb:
    db_host: port0.mf
    db_port: 5432
    db_name: test
    db_user: user42
    db_password: passw0rd

    # configure table creation (enabled for all tables by default):
    create_table:
      regexp: /.+/
      method: create_table # default is create_table. use create_hypertable for TimeScaleDB

    # # set the time precision and column.
    # # The default precision is microseconds, which is the highest precision
    # # PostgreSQL supports while influxdb protocol uses nanoseconds.
    # time:
    #   seconds # can be: seconds, milliseconds, microseconds
    #     time_field: time

    # # a two-field alternative with nanosecond precision
    # time:
    #   tz+nanoseconds
    #     time_field: time
    #     nano_field: nanoseconds

    # # set the name of tags column defaults to "tags"
    # tags_jsonb_column: tags
    # # set to null to disable. then tag columns are fixed and
    # # automatically determined from your unique index

    # # if you want to put fields in a JSONB column:
    # fields_jsonb_column: fields
    # # set to null disable. then fields columns are automatically
    # # created as needed but

    # TODO:
    # # if you want to define which tags make up the tags:
    # # (note that if tags_jsonb_column is set, then these
    # # limit which keys to use from it)
    # tag_colummns:
    #   - tag1
    #   - tag2

    # TODO:
    # # if you want to define which fields are permitted: (note that
    # # if fields_jsonb_column is set, then these limit which keys to
    # # use from it)
    # field_columns:
    #   - field1
    #   - field2

# TODO:
# regexp_databases:
#   - /(.*)/:
#     # regular expressions can also be used; evaluted from first to last

#     db_host: port0.mf
#     db_port: 5423

#     # not required:
#     db_name: $1
